### ISSUE TITLE
Bare gits needs to have refs/heads/ included in ref name (go-git.v4?)

### ISSUE THREAD

**Issue by GLundh** [google/zoekt#29] opened 2017-10-28 21:45 UTC
When trying out latest Zoekt (`@master`), it seems that the full branch name (**refs/heads/**master) needs to be specified for bare gits to allow Zoekt to actually index them.

In our previously deployed version of Zoekt (pre go-git.v4, so I'm guessing this is the change that brought on the issue) it was fine running `zoekt-git-index --branches  master,stable-*` on bare gits and have Zoekt indexing the specified branches. This is not the case anymore and is a bit problematic since the full ref-spec is now stored into the index and presented in the UI. 

When branches are presented as "refs/heads/master" in the UI it hinders readability and wastes screen real estate in the UI. I'm guessing this also this affects branch searches.
  
I can try making a patch for it, though I'm not sure if we should change how `zoekt-git-index` interpret branch names, or just change how the UI presents the information.

**Comment by hanwen** [comment] 2017-10-30 10:14
yeah, this could have been the go-git transition. The relevant code would be under gitindex, and there is an option BranchPrefix that should hold refs/heads/ . The prefix should not go into the actual branch name, afaict:

https://gerrit.googlesource.com/zoekt/+/f3e8b54db17ec67f8108123bac197194f51d1288/gitindex/git.go#342

maybe expandBranches doesn't behave as expected?

**Comment by GLundh** [comment] 2017-10-31 11:32
Sven made a match which seems to work for us: 

https://gerrit-review.googlesource.com/c/zoekt/+/137410

**Comment by hanwen** [comment] 2017-11-05 13:05
can you tell me more about the failure mode? I can't reproduce the problem.

$ git clone --mirror https://gerrit.googlesource.com/zoekt
$ cd zoekt.git
$ git show-ref|grep master
e25552763cd3c371a52cda438d8e194b775b8072 refs/heads/master
$ zoekt-git-index --branches=master .
2017/11/05 14:03:11 finished /home/hanwen/.zoekt/gerrit.googlesource.com_zoekt_v14.00000.zoekt: 1261902 index bytes (overhead 3.4)

**Comment by GLundh** [comment] 2017-11-06 10:43
That will work because the default -prefix is "refs/heads/".

Since we index Gerrit configurations (refs/meta/config) we need to set "-prefix" to an empty string or else we cannot index the "refs/meta/"-branches.

Pre go-git.v4 we could set -prefix to "" and it would still find and index a ref like "master". That way we could index both "master" (**not** "refs/heads/master") and "refs/meta/config", which was perfect for us.

Since go-git.v4, zoekt-git-index wont find "master" anymore with -prefix "", so we have to specify the full branch ref: "refs/heads/master" which clutters the UI (and I guess affect the searches).

I guess people that index refs/notes and similar namespaces will have the same problem.

**Comment by sselberg** [comment] 2017-11-06 10:54
This problem is solved by this patch:
https://gerrit-review.googlesource.com/c/zoekt/+/137410

**Comment by hanwen** [comment] 2017-11-06 19:45
fixed by https://github.com/google/zoekt/commit/e1a95db42e6a5292b63b6f5a9a4e2d24ffcbbd68

**Closed by hanwen** 2017-11-06 19:45 UTC
